# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38654ca818517b4205f51f14c948309a31afe304136aa8e32277ddfb017863ff1370ca7a3eaa231a35a35c105494e08e1705d7140c76a9a709701fdf422ce8a6

test:
  secret_key_base: 3a717482064d5241ae65f468b0bb605ab3c76d4f452ada01e5abb21c661c1c91bff812ca56418d7b8d9c2b0924a5941c1de0aae77479dbbe9c460f6e5674619a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
